<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BsDirectory\Module'                        => __DIR__ . '/Module.php',
    'BsDirectory\Controller\IndexController' => __DIR__ . '/src/BsDirectory/Controller/IndexController.php',
    'BsDirectoryTest\Framework\TestCase'        => __DIR__ . '/tests/BsDirectory/Framework/TestCase.php',
    'BsDirectoryTest\SampleTest'                => __DIR__ . '/tests/BsDirectory/SampleTest.php',
);
